- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
          - name:  Ajustando o Timezone do Servidor
            timezone:
                    name: America/Sao_Paulo

- hosts: controllers
  remote_user: vagrant
  become: yes
  tasks:
          - name: Criando o Arquivo Info
            lineinfile:
                  path: /tmp/info
                  line: SERVIDOR ANSIBLE CONTROLLER
                  create: yes

- hosts: database
  remote_user: vagrant
  become: yes
  tasks:
          - name: Criando o Arquivo Info
            lineinfile:
                  path: /tmp/info
                  line: SERVIDOR DE BANCO DE DADOS MYSQL
                  create: yes
          - name: Instalacao do My SQL no Servidor
            apt:
                    state: present
                    pkg:
                            - mysql-server

- hosts: webservers
  remote_user: vagrant
  become: yes
  tasks:
         - name: Criando o Arquivo Info
           lineinfile:
                 path: /tmp/info
                 line: SERVIDOR DO BLOG WORDPRESS
                 create: yes

         - name: Instalacao do WordPress no Servidor
           apt:
                   state: present
                   pkg:
                          - apache2
                          - php-curl
                          - php-gd
                          - php-mbstring
                          - php-xml
                          - php-xmlrpc
                          - php-soap
                          - php-intl
                          - php-zip
                          - php
                          - libapache2-mod-php
                          - php-mysql
                          - php-cli

